### ISSUE TITLE
Merge feature

### ISSUE THREAD

**Issue by arrowd** [andys8/git-brunch#23]
Hello.

It'd be great if `git-brunch` would support merging feature, which would do the same thing as `git merge somebranch` from command line. This way it'd be possible to quickly merge and delete feature branches.

**Comment by andys8** [comment]
Closed by #24

**Comment by arrowd** [comment]
Awesome, thanks!

It'd be great if you push a new release to Hackage soon, so I can update the FreeBSD package.

**Comment by andys8** [comment]
Good idea to add merge. Makes sense because there is `rebase`. Release done :)

**Comment by arrowd** [comment]
Wohoo, thanks again.
