### ISSUE TITLE
Terminal encoding breaks after quitting `git brunch`

### ISSUE THREAD

**Issue by pehota** [andys8/git-brunch#7]
Hey @andys8 ,
I noticed that after I quit the app, special characters in the terminal no longer show up correctly. 
Attached are screenshots of the issue and my machine's setup.

![image](https://user-images.githubusercontent.com/10498221/78019973-dc5ece00-7350-11ea-9438-b377865510ad.png)

![image](https://user-images.githubusercontent.com/10498221/78019837-9d307d00-7350-11ea-9cae-1df36dd3fb3d.png)

**Comment by andys8** [comment]
Hey @pehota,

Is it it only for the next character or happening in other lines, too? The only thing I can think of is how the program is exiting with regards to line breaks. Maybe we can have a look or you can try to come up with a bugfix for the issue. I'm not experiencing the behavior but haven't tried to reproduce it by changing my setup.

**Comment by pehota** [comment]
After installing from AUR issue is gone. False alarm.
